PC端管理员
GreenNerd/concierge-fe pull request #1
Opened 2018-04-10 10:04 UTC by breeze0

2018-04-11 01:56 UTC, breeze0 commented
@fahchen

2018-04-16 01:40 UTC, moonRider requested changes

2018-04-16 01:40 UTC, moonRider commented on index.html
> +    <script type="text/javascript" src="http://webapi.amap.com/maps?v=1.4.4&key=d2deaa9c3fab926880606fed18cd53c9"></script>
这脚本会阻塞渲染呀

2018-04-16 01:40 UTC, moonRider commented on src/components/cover_picker.vue
> +        },2000)
2000的标准是从何而来？

2018-04-16 01:40 UTC, moonRider commented on src/components/cover_picker.vue
> +              'Authorization': this.getCookie('token')
token应该缓存下，上面也用了

2018-04-16 01:40 UTC, moonRider commented on src/components/map.vue
> +      updateValue(args) {
这个方法在mapClick里面应该用得上

2018-04-16 01:40 UTC, moonRider commented on src/pages/form.vue
> +        formData.append('name',this.form.name);
我觉得这个地方应该封装下，上面也用了2次了

2018-04-18 02:54 UTC, breeze0 commented
重构了下代码 @moonRider

2018-04-20 09:34 UTC, fahchen commented
@moonRider 通过的话，你点击上面按钮把它合并了

2018-04-23 07:32 UTC, moonRider requested changes

2018-04-23 07:32 UTC, moonRider commented on src/components/map.vue
> +          this.currentLatitude = event.data.location.lat;
这地方用updateValue去更新呀

2018-04-23 07:32 UTC, moonRider commented on src/pages/form.vue
> +        this.form.address = this.$refs.addressPickerRef.getData().address;
思考下多次取 this.$refs.addressPickerRef.getData() 和 缓存这个的区别

2018-04-23 07:32 UTC, moonRider commented on src/components/time_setter.vue
> +        weekdays: [
这个由上面的const演变吧，这样只用维护一个地方

2018-04-23 07:32 UTC, moonRider commented on src/components/map.vue
> +      mapInit() {
这个方法太长了，把一些逻辑适当的拆分成小的私有函数，顾名思义，读代码的时候别人就知道你的逻辑大致是怎么的

2018-04-23 07:34 UTC, moonRider commented
@breeze0

2018-04-25 09:35 UTC, breeze0 commented on src/components/map.vue
> +          this.currentLatitude = event.data.location.lat;
这个确实把数据封装下传入updateValue就可以了

2018-04-25 09:36 UTC, breeze0 commented on src/components/map.vue
> +      mapInit() {
我把这里面的每个控件的注册都作为methods里面的方法来调用，可读性应该更强一点了。

2018-04-25 09:49 UTC, breeze0 commented
@moonRider

2018-05-02 08:00 UTC, moonRider requested changes

2018-05-02 08:00 UTC, moonRider commented on src/components/map.vue
> +          this.currentLatitude = lat;
这种用updatePosition之类的方法去更新，后面也是，然后这个方法还是太长了，想办法拆分下

2018-05-02 08:00 UTC, moonRider commented on src/components/map.vue
> +                this.currentLatitude = lat;
这里同上

2018-05-02 08:00 UTC, moonRider commented on src/pages/form.vue
> +        formData.append('name',this.form.name);
这个地方，能把这段代码抽象下更好，挨个写看着蛋疼

2018-05-04 01:44 UTC, merged